fixture_data = {
    ('gnirs', 'N20160523S0191.fits'): ['GNIRS', 'GEMINI_NORTH', 'SIDEREAL', 'LS', 'SPECT', 'UNPREPARED', 'RAW'],
    ('nifs', 'N20160428S0174.fits') : ['NIFS', 'IFU', 'GEMINI_NORTH', 'AZEL_TARGET', 'NON_SIDEREAL', 'SPECT', 'UNPREPARED', 'RAW'],
    ('gmos', 'S20051225S0084.fits') : ['GMOS', 'IFU', 'BLUE', 'SIDEREAL', 'SPECT', 'GEMINI_SOUTH', 'RAW', 'UNPREPARED'],
    ('gmos', 'N20160616S0431.fits') : ['GMOS', 'ARC', 'GEMINI_NORTH', 'LS', 'AZEL_TARGET', 'CAL', 'SPECT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos', 'N20160516S0485.fits') : ['GMOS', 'AT_ZENITH', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos', 'S20060131S0122.fits') : ['GMOS', 'IFU', 'BLUE', 'SIDEREAL', 'SPECT', 'GEMINI_SOUTH', 'RAW', 'UNPREPARED'],
    ('gmos', 'N20160407S0076.fits') : ['GMOS', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos', 'N20111124S0203.fits') : ['GMOS', 'IFU', 'IFU_RED', 'IFU', 'GEMINI_NORTH', 'FLAT', 'CAL', 'SIDEREAL', 'SPECT', 'RAW', 'UNPREPARED'],
    ('gmos', 'N20160516S0485_bias.fits') : ['GMOS', 'AT_ZENITH', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED_BIAS'],
    ('gmos', 'S20120815S0031.fits') : ['GMOS', 'IMAGE', 'SIDEREAL', 'IMAGE', 'GEMINI_SOUTH', 'RAW', 'UNPREPARED'],
}
