fixture_data = {
# GMOS-Level Tags 
#   Tags: GMOS, BIAS, DARK, FRINGE, FLAT (whether it's GCAL or TWILIGT), GCALFLAT, TWILIGHT, ARC, IMAGE, SPECT, IFU, LS, MOS, NODANDSHUFFLE, BLUE, RED, TWO
#
#        GMOS Bias
#             I don't know why the North bias don't have the 'AT_ZENITH'
    ('gmos-n', 'N20110524S0358.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'GMOS', 'BIAS', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-n', 'N20110524S0358_bias.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'GMOS', 'BIAS', 'CAL', 'NON_SIDEREAL', 'OVERSCAN_SUBTRACTED', 'OVERSCAN_TRIMMED', 'PREPARED', 'PROCESSED'],
    ('gmos-s', 'S20110627S0151.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'GEMINI', 'SOUTH', 'GMOS', 'BIAS', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-s', 'S20070318S0274_bias.fits'): ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'GEMINI', 'SOUTH', 'GMOS', 'BIAS', 'NON_SIDEREAL', 'OVERSCAN_SUBTRACTED', 'OVERSCAN_TRIMMED', 'PREPARED', 'PROCESSED'],

#        GMOS Imaging Data
    ('gmos-n', 'N20120203S0284.fits') : ['GEMINI', 'NORTH', 'GMOS', 'IMAGE', 'SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-s', 'S20111120S0478.fits') : ['GEMINI', 'SOUTH', 'GMOS', 'IMAGE', 'SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-n', 'N20120121S0175.fits') : ['ACQUISITION', 'GEMINI', 'NORTH', 'GMOS', 'IMAGE', 'SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-n', 'N20110718S0294.fits') : ['CAL', 'GEMINI', 'NORTH', 'GMOS', 'IMAGE', 'FLAT', 'TWILIGHT', 'SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-n', 'N20110718S0290_flat.fits') : ['CAL', 'GEMINI', 'NORTH', 'GMOS', 'IMAGE', 'FLAT', 'TWILIGHT', 'SIDEREAL', 'OVERSCAN_SUBTRACTED', 'OVERSCAN_TRIMMED', 'PREPARED', 'PROCESSED'],
    ('gmos-s', 'S20150903S0061.fits') : ['ACQUISITION', 'GEMINI', 'SOUTH', 'GMOS', 'IMAGE', 'SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gmos-s', 'S20140625S0361.fits') : ['CAL', 'GEMINI', 'SOUTH', 'GMOS', 'IMAGE', 'FLAT', 'TWILIGHT', 'SIDEREAL', 'RAW', 'UNPREPARED'],

#  GMOS Longslit Data
    ('gmos-s', 'S20091217S0032.fits') : ['GEMINI', 'SOUTH', 'GMOS', 'LS', 'NODANDSHUFFLE', 'RAW', 'SPECT', 'SIDEREAL', 'UNPREPARED'],

#  GMOS MOS Data
    ('gmos-n', 'N20110826S0336.fits') : ['GEMINI', 'NORTH', 'GMOS', 'MOS', 'RAW', 'SPECT', 'SIDEREAL', 'UNPREPARED'],
    ('gmos-s', 'S20150417S0092.fits') : ['GEMINI', 'SOUTH', 'GMOS', 'MOS', 'NODANDSHUFFLE', 'RAW', 'SPECT', 'SIDEREAL', 'UNPREPARED'],

# NIRI Data
#   NIRI Darks
    ('niri', 'N20131215S0503.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'NIRI', 'DARK', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('niri', 'N20130409S0105_dark.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'NIRI', 'DARK', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED'],

#   NIRI Imaging
    ('niri', 'N20131215S0178_prepared.fits') : ['GEMINI', 'NORTH', 'IMAGE', 'NIRI', 'PREPARED', 'SIDEREAL'],
    ('niri', 'N20131215S0178.fits') : ['GEMINI', 'NORTH', 'IMAGE', 'NIRI', 'RAW', 'SIDEREAL', 'UNPREPARED'],
    ('niri', 'N20131215S0427.fits') : ['AZEL_TARGET', 'CAL', 'GCAL_IR_OFF', 'GEMINI', 'NORTH', 'IMAGE', 'NIRI', 'FLAT', 'GCALFLAT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED', 'LAMPOFF'],
    ('niri', 'N20131215S0428.fits') : ['AZEL_TARGET', 'CAL', 'GCAL_IR_ON', 'GEMINI', 'NORTH', 'IMAGE', 'NIRI', 'FLAT', 'GCALFLAT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED', 'LAMPON'],
    ('niri', 'N20130404S0470.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'GCAL_IR_OFF', 'GEMINI', 'NORTH', 'IMAGE', 'NIRI', 'FLAT', 'GCALFLAT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED', 'LAMPOFF'],

# GNIRS Data
#   GNIRS Darks
    ('gnirs', 'N20140812S0150.fits') :
       ['AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'GNIRS', 'DARK', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gnirs', 'N20140812S0142_dark.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'NORTH', 'GNIRS', 'DARK', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED'],

#   GNIRS Imaging
    ('gnirs', 'N20120117S0019.fits') : ['GEMINI', 'NORTH', 'GNIRS', 'IMAGE', 'RAW', 'SIDEREAL', 'UNPREPARED'],
    ('gnirs', 'N20140717S0232.fits') : ['ACQUISITION', 'GEMINI', 'NORTH', 'GNIRS', 'IMAGE', 'RAW', 'SIDEREAL', 'UNPREPARED'],
    ('gnirs', 'N20120117S0041.fits') : ['CAL', 'GCAL_IR_ON', 'GEMINI', 'NORTH', 'GNIRS', 'IMAGE', 'FLAT', 'GCALFLAT', 'RAW', 'SIDEREAL', 'UNPREPARED', 'LAMPON'],
    ('gnirs', 'N20120117S0042.fits') : ['CAL', 'GCAL_IR_OFF', 'GEMINI', 'NORTH', 'GNIRS', 'IMAGE', 'FLAT', 'GCALFLAT', 'RAW', 'SIDEREAL', 'UNPREPARED', 'LAMPOFF'],
    ('gnirs', 'N20131222S0070_flat.fits') : ['CAL', 'GEMINI', 'NORTH', 'GNIRS', 'IMAGE', 'FLAT', 'GCALFLAT', 'PREPARED', 'PROCESSED', 'SIDEREAL'],
 
#   GNIRS Longslit
    ('gnirs', 'N20110826S0155.fits') : ['GEMINI', 'NORTH', 'GNIRS', 'LS', 'SPECT', 'RAW', 'SIDEREAL', 'UNPREPARED'],

# NIFS Data
#   NIFS IFU
    ('nifs', 'N20110707S0196.fits') : ['GEMINI', 'NORTH', 'IFU', 'NIFS', 'SPECT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],

# F2 Data
#   F2 Darks
    ('f2', 'S20150516S0373.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'F2', 'DARK', 'GEMINI', 'SOUTH', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('f2', 'S20141031S0274_dark.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'F2', 'DARK', 'GEMINI', 'SOUTH', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED'],

#   F2 Imaging
    ('f2', 'S20150511S0168.fits') : ['F2', 'IMAGE', 'GEMINI', 'SOUTH', 'RAW', 'SIDEREAL', 'UNPREPARED'],
    ('f2', 'S20150511S0274.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'F2', 'IMAGE', 'FLAT', 'GCALFLAT', 'GCAL_IR_ON', 'GEMINI', 'SOUTH', 'NON_SIDEREAL', 'RAW', 'UNPREPARED', 'LAMPON'],
    ('f2', 'S20150511S0275.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'F2', 'IMAGE', 'FLAT', 'GCALFLAT', 'GCAL_IR_OFF', 'GEMINI', 'SOUTH', 'NON_SIDEREAL', 'RAW', 'UNPREPARED', 'LAMPOFF'],
    ('f2', 'S20141107S0062_flat.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'CAL', 'F2', 'IMAGE', 'FLAT', 'GCALFLAT', 'GEMINI', 'SOUTH', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED'],

# GSAOI Data
#   GSAOI Imaging
    ('gsaoi', 'S20150110S0142.fits') : ['GEMINI', 'SOUTH', 'GSAOI', 'IMAGE', 'RAW', 'SIDEREAL', 'UNPREPARED'],
    ('gsaoi', 'S20150105S0206.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'SOUTH', 'GSAOI', 'IMAGE', 'FLAT', 'DOMEFLAT', 'LAMPOFF', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gsaoi', 'S20150105S0167.fits') : ['AZEL_TARGET', 'CAL', 'GEMINI', 'SOUTH', 'GSAOI', 'IMAGE', 'FLAT', 'DOMEFLAT', 'LAMPON', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
    ('gsaoi', 'S20130524S0081_flat.fits') : ['CAL', 'GEMINI', 'SOUTH', 'GSAOI', 'IMAGE', 'FLAT', 'DOMEFLAT', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED'],

#    ('bhros', 'S20070131S0030.fits') : ['BHROS', 'SIDEREAL', 'GEMINI_SOUTH', 'SPECT', 'UNPREPARED', 'RAW'],
#    ('bhros', 'S20070131S0152.fits') : ['AT_ZENITH', 'BHROS', 'AZEL_TARGET', 'NON_SIDEREAL', 'GEMINI_SOUTH', 'SPECT', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20150629S0208.fits') : ['MOS', 'SPECT', 'F2', 'NON_SIDEREAL', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20150629S0245.fits') : ['FLAT', 'AT_ZENITH', 'GCAL_IR_ON', 'AZEL_TARGET', 'MOS', 'SPECT', 'F2', 'CAL', 'NON_SIDEREAL', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20150629S0244.fits') : ['AT_ZENITH', 'ARC', 'AZEL_TARGET', 'MOS', 'SPECT', 'F2', 'CAL', 'NON_SIDEREAL', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20160616S0072.fits') : ['GCAL_IR_ON', 'FLAT', 'SIDEREAL', 'SPECT', 'F2', 'CAL', 'LS', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20160616S0075.fits') : ['IMAGE', 'SIDEREAL', 'F2', 'ACQUISITION', 'IMAGE', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20160708S0025.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'DARK', 'F2', 'CAL', 'NON_SIDEREAL', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('f2', 'S20160616S0071.fits') : ['ARC', 'SIDEREAL', 'SPECT', 'F2', 'CAL', 'LS', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('gmos', 'S20051225S0084.fits') : ['GMOS', 'IFU', 'BLUE', 'SIDEREAL', 'SPECT', 'GEMINI_SOUTH', 'RAW', 'UNPREPARED'],
#    ('gmos', 'N20160616S0431.fits') : ['GMOS', 'ARC', 'GEMINI_NORTH', 'LS', 'AZEL_TARGET', 'CAL', 'SPECT', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
#    ('gmos', 'N20160516S0485.fits') : ['GMOS', 'AT_ZENITH', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
#    ('gmos', 'N20160407S0076.fits') : ['GMOS', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'RAW', 'UNPREPARED'],
#    ('gmos', 'N20111124S0203.fits') : ['GMOS', 'IFU', 'RED', 'GEMINI_NORTH', 'FLAT', 'CAL', 'SIDEREAL', 'SPECT', 'RAW', 'UNPREPARED'],
#    ('gmos', 'N20160516S0485_bias.fits') : ['GMOS', 'AT_ZENITH', 'GEMINI_NORTH', 'BIAS', 'AZEL_TARGET', 'CAL', 'NON_SIDEREAL', 'PREPARED', 'PROCESSED_BIAS'],
#    ('gmos', 'S20120815S0031.fits') : ['GMOS', 'IMAGE', 'SIDEREAL', 'IMAGE', 'GEMINI_SOUTH', 'RAW', 'UNPREPARED'],
#    ('gnirs', 'N20160523S0191.fits'): ['GNIRS', 'GEMINI_NORTH', 'SIDEREAL', 'LS', 'SPECT', 'UNPREPARED', 'RAW'],
#    ('gpi', 'S20160523S0215.fits') : ['GPI', 'IFU', 'NON_SIDEREAL', 'SPECT', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('gsaoi', 'S20150531S0009.fits') : ['FLAT', 'TWILIGHT', 'SIDEREAL', 'CAL', 'IMAGE', 'GSAOI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('gsaoi', 'S20160422S0150.fits') : ['AT_ZENITH', 'AZEL_TARGET', 'DARK', 'CAL', 'IMAGE', 'NON_SIDEREAL', 'GSAOI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('gsaoi', 'S20160422S0092.fits') : ['SIDEREAL', 'IMAGE', 'GSAOI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('gsaoi', 'S20160613S0316.fits') : ['DOMEFLAT', 'FLAT', 'AZEL_TARGET', 'CAL', 'IMAGE', 'NON_SIDEREAL', 'GSAOI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('michelle', 'N20030625S0075.fits') : ['GEMINI_NORTH', 'MICHELLE', 'SIDEREAL', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20130715S0112.fits') : ['IMAGE', 'SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20130607S0592.fits') : ['IMAGE', 'AZEL_TARGET', 'DARK', 'CAL', 'NON_SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20130714S0155.fits') : ['CAL', 'FLAT', 'IMAGE', 'GCAL_IR_ON', 'SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20130607S0258.fits') : ['ADI_R', 'IMAGE', 'SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20091206S0101.fits') : ['AT_ZENITH', 'CAL', 'FLAT', 'IMAGE', 'AZEL_TARGET', 'NON_SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nici', 'S20130806S0071.fits') : ['ASDI', 'IMAGE', 'SIDEREAL', 'NICI', 'GEMINI_SOUTH', 'UNPREPARED', 'RAW'],
#    ('nifs', 'N20160428S0174.fits') : ['NIFS', 'IFU', 'GEMINI_NORTH', 'AZEL_TARGET', 'NON_SIDEREAL', 'SPECT', 'UNPREPARED', 'RAW'],
#    ('niri', 'N20160523S0471_forStack.fits') : ['NIRI', 'GEMINI_NORTH', 'SIDEREAL', 'IMAGE', 'PREPARED'],
#    ('niri', 'N20120505S0564.fits') : ['NIRI', 'GEMINI_NORTH', 'AZEL_TARGET', 'SPECT', 'LS', 'NON_SIDEREAL', 'GCAL_IR_OFF', 'UNPREPARED', 'RAW'],
#    ('niri', 'N20160522S0004.fits') : ['NIRI', 'GEMINI_NORTH', 'SIDEREAL', 'IMAGE', 'UNPREPARED', 'RAW'],
}
