# This dictionary relates the function name (used in DataSpider.py) with the
# actual descriptor name
# Function name is the key, descriptor name is the value
functionDict = {
    "airmass":"AIRMASS",
    "camera":"CAMERA",
    "cwave":"CWAVE",
    "datasec":"DATASEC",
    "detsec":"DETSEC",
    "disperser":"DISPERSR",
    "exptime":"EXPTIME",
    "filterid":"FILTID",
    "filtername":"FILTNAME",
    "fpmask":"FPMASK",
    "gain":"GAIN",
    "instrument":"INSTRUME",
    "mdfrow":"MDFROW",
    "nonlinear":"NONLINEA",
    "nsciext":"NSCIEXT",
    "object":"OBJECT",
    "obsmode":"OBSMODE",
    "pixscale":"PIXSCALE",
    "pupilmask":"PUPILMSK",
    "rdnoise":"RDNOISE",
    "satlevel":"SATLEVEL",
    "utdate":"UTDATE",
    "uttime":"UTTIME",
    "wdelta":"WDELTA",
    "wrefpix":"WREFPIX",
    "xccdbin":"XCCDBIN",
    "yccdbin":"YCCDBIN",
    }
