# pre-commit configuration for DRAGONS
#
# Please follow these guidelines:
#
# 1) All linting behavior can & should be defined in this file. For example,
#    that includes:
#
#    + Formatting
#    + Syntax/type checks
#    + Commit protections/standards
#
# 2) Do not include any tests involving the execution of this software, under
#    any circumstances.
#
# 3) This should be a superset of the NOIRLab Python Standard, which can be
#    found here:
#
#    https://github.com/teald/python-standard-template/blob/main/.pre-commit-config.yaml
default_stages: [pre-commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-docstring-first
    exclude: "archived/"
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: forbid-submodules
