stdkeyDictNIRI = {
    "key_niri_avdduc":"A_VDDUC",
    "key_niri_avdet":"A_VDET",
    "key_niri_camera":"CAMERA",
    "key_niri_cd11":"CD1_1",
    "key_niri_cd12":"CD1_2",
    "key_niri_cd21":"CD2_1",
    "key_niri_cd22":"CD2_2",
    "key_niri_coadds":"COADDS",
    "key_niri_cwave":"CWAVE",
    "key_niri_exptime":"EXPTIME",
    "key_niri_filter1":"FILTER1",
    "key_niri_filter2":"FILTER2",
    "key_niri_filter3":"FILTER3",
    "key_niri_fpmask":"FPMASK",
    "key_niri_lnrs":"LNRS",
    "key_niri_ndavgs":"NDAVGS",
    }
