#!/usr/bin/env python
import os
#===============================================================================
# 
# The output tar file will be above the gemini_python folder.
#
#===============================================================================
'''
CONFIG VALUES
'''

execfile( 'tempConfig.py' )
recdat = 'gemini_python/test_data/recipedata/'
trunk = TRUNK_PATH

tarname = 'recipedemo.tar.gz'

files = [recdat+'N20090822S0207_bias.fits',
         recdat+'N20090825S0114_flat.fits',
         #recdat+'N20090414S0102_flat.fits',
         #recdat+'N20090823S0102_flat.fits',
         #recdat+'N20090415S1011_bias.fits',
         #recdat+'N20090502S0397_flat.fits',
         #recdat+'N20020214S022_bias.fits',
         #recdat+'N20020211S156_flat.fits',
         #recdat+'N20020507S0045_bias.fits',
         #recdat+'N20020606S0149_flat.fits',
         
         #recdat+'N20091002S0219.fits',
         
         #recdat+'N20020214S059.fits',
         #recdat+'N20020214S060.fits',
         #recdat+'N20020214S061.fits',
         
         #recdat+'N20090703S0156.fits',
         #recdat+'N20090703S0157.fits',
         #recdat+'N20090703S0158.fits',
         #recdat+'N20090703S0159.fits',
         #recdat+'N20090703S0160.fits',
         #recdat+'N20090703S0161.fits',
         #recdat+'N20090703S0162.fits',
         #recdat+'N20090703S0163.fits',
         
         recdat+'N20091027S0133.fits',
         recdat+'N20091027S0134.fits',
         recdat+'N20091027S0135.fits',
         recdat+'N20091027S0136.fits',
         recdat+'N20091027S0137.fits',
         
         #recdat+'N20091027S0138.fits',
         #recdat+'N20091027S0139.fits',
         #recdat+'N20091027S0140.fits',
         #recdat+'N20091027S0141.fits',
         #recdat+'N20091027S0142.fits',
         
         os.path.join(trunk,'astrodata/*.py'),
         #trunk+'astrodata/reduce',
         os.path.join(trunk,'astrodata/scripts/*'),
         os.path.join(trunk,'iqtool/*'),
         os.path.join(trunk,'ADCONFIG_Gemini'),
         os.path.join(trunk,'RECIPES_Gemini'),
         os.path.join(trunk,'utils'),
         os.path.join(CLEAN_PATH,'clean'),
         'rundemo',
         'packgempy',
         'tempConfig',
         ]

print "taring files, this will take some time..."
err = os.system( "tar -czf "+tarname+' '+' '.join(files) )
if err > 0:
    raise "Problem tarring the files."
print "Success: '"+tarname+"' can be found at:", os.getcwd()
