#!/usr/bin/env python
import os
import time
import sys
#===============================================================================
# 
# This file MUST be above the gemini_python folder in order to work.
#
#===============================================================================

'''
CONFIG VALUES
'''
execfile( 'tempConfig.py' )
pkg_path = os.path.abspath( 'PACKAGE_PATH' )
script_path = os.path.abspath( SCRIPTS_PATH )
reduce = os.path.join( script_path, 'reduce' )

#!!!
# Change the files in here to change which files will be run.
#!!!

filelist = [
#'N20091002S0219.fits'
#---
#'N20090703S0156.fits',
#'N20090703S0157.fits',
#'N20090703S0158.fits',
#'N20090703S0159.fits',
#'N20090703S0160.fits',
#'N20090703S0161.fits',
#'N20090703S0162.fits',
#'N20090703S0163.fits',
#----
'N20091027S0133.fits',
'N20091027S0134.fits',
'N20091027S0135.fits',
'N20091027S0136.fits',
'N20091027S0137.fits'
#----
#'N20091027S0138.fits',
#'N20091027S0139.fits',
#'N20091027S0140.fits',
#'N20091027S0141.fits',
#'N20091027S0142.fits'
#----
#'N20020214S059.fits',
#'N20020214S060.fits',
#'N20020214S061.fits'
			]
#!!!
# Change the recipe in here to change which recipe will be run.
#!!!
#recipe = 'demo'#'raTest2'


os.chdir( PACKAGE_PATH )

oldpypath = os.getenv( 'PYTHONPATH' )

print "Temporarily Changing PYTHONPATH"
os.environ.update({'PYTHONPATH':oldpypath+":"+os.path.abspath(TRUNK_PATH)+":"})
print 'PYTHONPATH', os.getenv( 'PYTHONPATH' )

try:
    os.chdir( TEST_DATA_PATH )
    os.system( os.path.join(CLEAN_PATH, 'clean') ) 
    filename = []
    for fits in filelist:
        filename.append( os.path.join( RECIPEDATA, fits ) )
    command = reduce + ' ' + ' '.join( filename )
    #command = reduce + ' -r ' + recipe + ' ' + filename
    print 'Command:\n', command
    start_time = time.time()
    os.system( command )
    end_time = time.time()
    print "Total Time:", (end_time - start_time)

except:
	print "Recipe failed for some reason"
finally:
	print "Changing PYTHONPATH back."
	os.environ.update( {'PYTHONPATH':oldpypath} )

print 'PYTHONPATH', os.getenv( 'PYTHONPATH' )

