#!/usr/bin/env python
import os
import time
import sys
#===============================================================================
# 
# This file MUST be above the gemini_python folder in order to work.
#
#===============================================================================

#!!!
# Change the files in here to change which files will be run.
#!!!

filelist = [
#'N20091002S0219.fits'
#---
#'N20090703S0156.fits',
#'N20090703S0157.fits',
#'N20090703S0158.fits',
#'N20090703S0159.fits',
#'N20090703S0160.fits',
#'N20090703S0161.fits',
#'N20090703S0162.fits',
#'N20090703S0163.fits',
#----
'N20091027S0133.fits',
'N20091027S0134.fits',
'N20091027S0135.fits',
'N20091027S0136.fits',
'N20091027S0137.fits'
#----
#'N20091027S0138.fits',
#'N20091027S0139.fits',
#'N20091027S0140.fits',
#'N20091027S0141.fits',
#'N20091027S0142.fits'
#----
#'N20020214S059.fits',
#'N20020214S060.fits',
#'N20020214S061.fits'
]

try:
    os.system( './clean' ) 
    recdat = 'recipedata/'
    start_time = time.time()
    fullflist = []
    for f in filelist:
        fullflist.append(recdat+f)
       
    if False:
        for fits in filelist:
            filename = recdat + fits
            #command = reduce + ' -r ' + recipe + ' ' + filename
            command = "reduce -m -r demo" + ' ' + filename 
            os.system( command )
    else:
    	precommand1 = "reduce --addcal recipedata/N20090825S0114_flat.fits --caltype=twilight " + " ".join(fullflist)
        precommand2 = "reduce --addcal recipedata/N20090415S1011_bias.fits --caltype=bias " + " ".join(fullflist)
        os.system(precommand1)
        os.system(precommand2)
        command = "reduce -m " + " ".join(fullflist) 
        print "command:", command
        os.system(command)
    
    end_time = time.time()
    print "Total Time:", (end_time - start_time)

except:
    print "Recipe failed for some reason"
    raise
