#!/usr/bin/env python
import os
import time
import sys
#===============================================================================
# 
# This file MUST be in the gemini_python/trunk/astrodata/scripts/ folder 
# and MUST be ran from gemini_python/test_data/ in order to work.
#
#===============================================================================

filelist = [
'N20100311S0090.fits',
'N20100311S0091.fits',
'N20100311S0092.fits',
'N20100311S0093.fits',
'N20100311S0094.fits',
'N20100311S0095.fits'
]

try:
    os.system( 'superclean -a' ) 
    recdat = 'GN-2010A-Q-1/'
    start_time = time.time()
    fullflist = []
    for f in filelist:
        fullflist.append(recdat+f)
       
    if False:
        for fits in filelist:
            filename = recdat + fits
            #command = reduce + ' -r ' + recipe + ' ' + filename
            command = "reduce -m -r NEWdemo" + ' ' + filename 
            os.system( command )
    else:
        command = "reduce -m -r NEWdemo " + " ".join(fullflist)+ ' --verbose=6' 
        print "command: ", command
        os.system(command)
    
    end_time = time.time()
    print "Total Time:", (end_time - start_time)

except:
    print "Recipe failed for some reason"
    raise
