#PACKAGE_PATH = '~/workspace'
#PACKAGE_PATH = '~/raDebug'
#PACKAGE_PATH = '/home/rallen/workspace'
#PACKAGE_PATH = os.path.abspath( '' )
PACKAGE_PATH = './'
#PACKAGE_PATH = '~/recipedemo'
#PACKAGE_PATH = os.getcwd()
TEST_DATA_PATH = os.path.join( PACKAGE_PATH, 'gemini_python/test_data' )
TRUNK_PATH = os.path.join( PACKAGE_PATH, 'gemini_python/trunk' )
SCRIPTS_PATH = os.path.join( TRUNK_PATH, 'astrodata/scripts' )
CLEAN_PATH = TEST_DATA_PATH
RECIPEDATA = 'recipedata/'
