stdkeyDictTRECS = {
    "key_trecs_airmass":"AIRMASS",
    "key_trecs_biaslevel":"BIASLEVL",
    "key_trecs_camera":"OBSMODE",
    "key_trecs_disperser":"GRATING",
    "key_trecs_exptime":"OBJTIME",
    "key_trecs_filter1":"FILTER1",
    "key_trecs_filter2":"FILTER2",
    "key_trecs_fpmask":"SLIT",
    "key_trecs_instrument":"INSTRUME",
    "key_trecs_object":"OBJECT",
    "key_trecs_obsmode":"OBSMODE",
    "key_trecs_pupilmask":"PUPILIMA",
    "key_trecs_utdate":"DATE-OBS",
    "key_trecs_uttime":"UT",
    }
