dependencies:
  - python=3.6
  - astropy
  - coverage
  - coveralls
  - cython
  - future
  - ipython
  - sphinx_rtd_theme
  - pip
  - pydocstyle
  - pytest
  - pylint
  - scipy
  - sextractor
  - sqlalchemy
  - astropy::astroquery
  - chroxvi::radon
  - conda-forge::python-dateutil
  - conda-forge::twine
  - omnia::behave
  - pip:
    - stsci.numdisplay
