keyword_comments = {
    # Dictionary keys are header keywords that are commonly updated
    # Dictionary values are standard comments for each keyword
    "ACQSLITS": "Locations of acquisition slits",
    "AMPNAME": "Amplifier name(s)",
    "ARRAYSEC": "Array section(s)",
    "BIASIM": "Bias image used",
    "BPMNAME": "Name of BPM used to identify bad pixels",
    "BUNIT": "Physical units of the array values",
    "CCDNAME": "CCD chip name(s)",
    "CCDSEC": "CCD section(s)",
    "CTYPE1": "Coordinate name represented by axis 1",
    "CTYPE2": "Coordinate name represented by axis 2",
    "CD1_1": "WCS matrix element 1 1",
    "CD1_2": "WCS matrix element 1 2",
    "CD2_1": "WCS matrix element 2 1",
    "CD2_2": "WCS matrix element 2 2",
    "CRPIX1": "Ref pix of axis 1",
    "CRPIX2": "Ref pix of axis 2",
    "CRVAL1": "RA at Ref pix in decimal degrees",
    "CRVAL2": "DEC at Ref pix in decimal degrees",
    "DARKIM": "Dark image used",
    "DATALAB": "DHS data label",
    "DATASEC": "Data section(s)",
    "DEC": "Declination of Target",
    "DETSEC": "Detector section(s)",
    "DISPAXIS": "Dispersion axis",
#    "EXPSCALE": "Scaling factor to match exposure time",
    "EXPTIME": "Exposure time [seconds]",
    "EXTCURVE": "Extinction curve used to correct to zero airmass",
    "FILTER": "Combined filter name",
    "FLATIM": "Flat image used",
    "FRINGEIM": "Fringe image used",
    "GAIN": "Gain [electrons/data value]",
    "GAINSET": "Gain setting (low / high)",
    "GEMPRGID": "Gemini program ID",
    "MEANFWHM": "Mean point source FWHM [arcsec]",
    "MEANELLP": "Mean point source ellipticity",
    "MEANZP": "Mean zero point",
    "MBG_SKYL": "Sky level measured from image",
    "MBG_SKSD": "Std Dev of MBG_SKYL",
    "MBG_BG": "Sky Background measures from image [mag/sq arcsec]",
    "MBG_BGSD": "Std Dev of MBG_BG",

    "MIQ_AOSE": "MeasureIQ AO Seeing [arcsec]",
    "MIQ_EE50": "MeasureIQ 50pc Enc Energy Diameter [arcsec]",
    "MIQ_EESD": "Std Dev of MIQ_EE50 [arcsec]",
    "MIQ_ELLP": "MeasureIQ mean ellipticity",
    "MIQ_ELSD": "Std Dev of MIQ_ELLP",
    "MIQ_FWHM": "MeasureIQ mean FWHM [arcsec]",
    "MIQ_FWSD": "Std Dev of MIQ_FWHM [arcsec]",
    "MIQ_ISOF": "MeasureIQ ISO FWHM [arcsec]",
    "MIQ_ISSD": "Std Dev of MIQ_ISOF [arcsec]",
    "MIQ_NSAM": "MeasureIQ Number of Samples",
    "MIQ_PA": "MeasureIQ Mean Position Angle [degree]",
    "MIQ_PASD": "Std Dev of MIQ_PA [degree]",
    "MIQ_STRE": "MeasureIQ Mean Strehll Ratio",
    "MIQ_STSD": "Std Dev of MIQ_STRE",
    "MIQ_ZEFW": "MeasureIQ Zenith FWHM",
    "MIQ_ZESD": "Std Dev of MIQ_ZEFW",
    "NAXIS1": "Axis length",
    "NAXIS2": "Axis length",
    "NCOMBINE": "Number of input images",
    "NEXTEND": "Number of extensions",
    "NONLINEA": "Non-linear regime [ADU]",
    "OBJECT": "Object Name",
    "OBSCLASS": "Observe class",
    "OBSID": "Observation ID / Data label",
    "OBSTYPE": "Observation type",
    "ORIGNAME": "Original filename prior to processing",
    "OVERRMS": "RMS of fit to overscan mean values",
    "OVERRDNS": "Readnoise estimate from overscan [electron]",
    "OVERSCAN": "Median of Overscan mean values",
    "OVERSEC": "Section used for overscan calculation",
    "PIXSCALE": "Pixel scale [arcsec/pixel]",
    "PROCLEVL": "Processing level. Uses IVOA obscore calib_level values",
    "RA": "Right Ascension",
    "RAWGEMQA": "Gemini Quality Assessment",
    "RAWPIREQ": "PI Requirements Met",
    "RAWBIAS": "Estimated raw bias level [ADU]",
    "RDNOISE": "Estimated read noise [electrons]",
    "REDUCEBG": "BG metric from reduced image",
    "REDUCEIQ": "IQ metric from reduced image",
    "RELEASE": "End of proprietary period YYYY-MM-DD",
    "RELINT": "Relative intensity factor",
    "SATLEVEL": "Saturation level [ADU]",
    "SKYLEVEL": "Sky level measured from image",
    "SLTILLIM": "Slit illumination image used",
    "SUBSKYBG": "Sky background subtracted",
    "TRIMMED": "Overscan section trimmed",
    "TRIMSEC": "Data section prior to trimming",
    "VARNOISE": "Types of noise included in VAR plane",
    "XTRACTLO": "Aperture lower limit",
    "XTRACTHI": "Aperture upper limit",
    "XTRACTRA": "RA of extracted spectrum",
    "XTRACTDE": "DEC of extracted spectrum",
}
