stdkeyDictMICHELLE = {
    "key_michelle_camera":"CAMERA",
    "key_michelle_cwave":"GRATPOS",
    "key_michelle_disperser":"GRATNAME",
    "key_michelle_exposure":"EXPOSURE",
    "key_michelle_filter":"FILTER",
    "key_michelle_fpmask":"SLITNAME",
    "key_michelle_gain":"GAIN",
    "key_michelle_numext":"NUMEXT",
    "key_michelle_numexpos":"NUMEXPOS",
    "key_michelle_obsmode":"MODE",
    "key_michelle_pixscale":"PIXELSIZ",
    "key_michelle_utdate":"UTDATE",
    "key_michelle_wdelta":"GRATDISP",
    }
