stdkeyDictNIFS = {
    "key_nifs_airmass":"AIRMASS",
    "key_nifs_bias":"BIASPWR",
    "key_nifs_camera":"INSTRUME",
    "key_nifs_coadds":"COADDS",
    "key_nifs_cwave":"GRATWAVE",
    "key_nifs_datasec":"DATASEC",
    "key_nifs_detsec":"DETSEC",
    "key_nifs_disperser":"GRATING",
    "key_nifs_exptime":"EXPTIME",
    "key_nifs_filter":"FILTER",
    "key_nifs_fpmask":"APERTURE",
    "key_nifs_instrument":"INSTRUME",
    "key_nifs_lnrs":"LNRS",
    "key_nifs_object":"OBJECT",
    "key_nifs_utdate":"DATE-OBS",
    "key_nifs_uttime":"UT",
    }
