GMOS_KeyDict = {
    "key_acqusition_slits":"ACQSLITS",
    "key_ampinteg":"AMPINTEG",
    "key_ampname":"AMPNAME",
    "key_array_section":"CCDSEC",
    "key_camera":"INSTRUME",
    "key_ccdsum":"CCDSUM",
    "key_central_wavelength":"GRWLEN",
    "key_array_name":"CCDNAME",
    "key_dec": "DEC",
    "key_detector_name":"DETID",
    "key_detector_type":"DETTYPE",
    "key_disperser":"GRATING",
    "key_dispersion":"CD1_1",
    "key_filter1":"FILTER1",
    "key_filter2":"FILTER2",
    "key_focal_plane_mask":"MASKNAME",
    "key_maskname":"MASKNAME",
    "key_masktype":"MASKTYP",
    "key_overscan_value":"OVERSCAN",
    "key_overscan_section":"BIASSEC",
    "key_ra": "RA",
    "key_wavelength_reference_pixel":"CRPIX1",
    "key_a_nod_count":"ANODCNT",
    "key_b_nod_count":"BNODCNT",
    }
