stdkeyDictGMOS = {
    "key_ampinteg":"AMPINTEG",
    "key_ampname":"AMPNAME",
    "key_camera":"INSTRUME",
    "key_ccdsum":"CCDSUM",
    "key_central_wavelength":"GRWLEN",
    "key_ccdname":"CCDNAME",
    "key_disperser":"GRATING",
    "key_dispersion":"CD1_1",
    "key_filter1":"FILTER1",
    "key_filter2":"FILTER2",
    "key_focal_plane_mask":"MASKNAME",
    "key_maskname":"MASKNAME",
    "key_masktype":"MASKTYP",
    "key_wavelength_reference_pixel":"CRPIX1",
    }
