#!/usr/bin/env python

#===============================================================================
# 
# The output tar file will be above the gemini_python folder.
#
#===============================================================================


import os

fullpath = os.path.abspath( __file__ )

index = fullpath.rfind( 'gemini_python' )
if index == -1:
    betterpath = './'
else:
    betterpath = fullpath[:index]

actualpath = "gemini_python/trunk/utils/"

rundemopath = os.path.join(betterpath, 'rundemo')
packgempath = os.path.join(betterpath, 'packgempy')
print "B.Path", betterpath
if not os.path.exists( rundemopath ):
    os.symlink(os.path.join(actualpath,'rundemo'), rundemopath )
if not os.path.exists( packgempath ):
    os.symlink(os.path.join(actualpath,'packgempy'), packgempath )

#if os.path.exists( os.path.join( betterpath, 'packgempy' ) ):
#	os.system( 'ln -s ' + 'packgempy ' + betterpath )

os.chdir( betterpath )

recdat = 'gemini_python/test_data/recipedata/'
trunk = 'gemini_python/trunk/'

tarname = 'recipedemo.tar.gz'

files = [recdat+'N20090822S0207_bias.fits',
         recdat+'N20090823S0102_flat.fits',
         recdat+'N20091002S0219.fits',
         recdat+'N20020214S059.fits',
         recdat+'N20020214S060.fits',
         recdat+'N20020214S061.fits',
         trunk+'astrodata/*.py',
         trunk+'astrodata/reduce',
         trunk+'ADCONFIG_Gemini',
         trunk+'RECIPES_Gemini',
         trunk+'utils',
         'gemini_python/test_data/clean',
         'rundemo',
         'packgempy'
         ]

print "taring files, this will take some time..."
err = os.system( "tar -czf "+tarname+' '+' '.join(files) )
if err > 0:
    raise "Problem tarring the files."
print "Tar file '"+tarname+"' can be found at:", betterpath
