#!/usr/bin/env python

#===============================================================================
# 
# The output tar file will be above the gemini_python folder.
#
#===============================================================================


import os

fullpath = os.path.abspath( __file__ )

index = fullpath.rfind( 'gemini_python' )
betterpath = fullpath[:index]
os.chdir( betterpath )

recdat = 'gemini_python/test_data/recipedata/'
trunk = 'gemini_python/trunk/'

tarname = 'recipedemo.tar.gz'

files = [recdat+'N20090822S0207_bias.fits',
         recdat+'N20090823S0102_flat.fits',
         recdat+'N20091002S0219.fits',
         recdat+'N20020214S059.fits',
         recdat+'N20020214S060.fits',
         recdat+'N20020214S061.fits',
         trunk+'astrodata/*.py',
         trunk+'astrodata/reduce',
         trunk+'ADCONFIG_Gemini',
         trunk+'RECIPES_Gemini',
         trunk+'utils',
         'gemini_python/test_data/clean'
         ]

print "taring files, this will take some time..."
os.system( "tar -czf "+tarname+' '+' '.join(files) )
print "Tar file '"+tarname+"' can be found at:", betterpath
