#!/usr/bin/env python
import os
import time
#===============================================================================
# 
# This file MUST be above the gemini_python folder in order to work.
#
#===============================================================================


#!!!
# Change the files in here to change which files will be run.
#!!!
'''

N20020214S059.fits
N20020214S060.fits
N20020214S061.fits
N20090822S0207_bias.fits
N20090823S0102_flat.fits
N20091002S0219.fits

'''
#filelist = ['N20091002S0219.fits']
filelist = [
#'N20091002S0219.fits'
'N20020214S059.fits',
'N20020214S060.fits',
'N20020214S061.fits'
			]
#!!!
# Change the recipe in here to change which recipe will be run.
#!!!
recipe = 'demo'#'raTest2'

oldpypath = os.getenv( 'PYTHONPATH' )
#print 'PYTHONPATH', os.getenv( 'PYTHONPATH' )

print "Temporarily Changing PYTHONPATH"
reduce = '../trunk/astrodata/reduce'
os.environ.update( {'PYTHONPATH':oldpypath + ":../trunk:"} )
#print 'PYTHONPATH', os.getenv( 'PYTHONPATH' )

try:
    os.chdir( 'gemini_python/test_data' )
    os.system( './clean' ) 
    recdat = 'recipedata/'
    start_time = time.time()
    for fits in filelist:
        filename = recdat + fits
        command = reduce + ' -r ' + recipe + ' ' + filename
        os.system( command )
    end_time = time.time()
    print "Total Time:", (end_time - start_time)

except:
	print "Recipe failed for some reason"
finally:
	print "Changing PYTHONPATH back."
	os.environ.update( {'PYTHONPATH':oldpypath} )

#print 'PYTHONPATH', os.getenv( 'PYTHONPATH' )

