keyword_comments = {
    # Dictionary keys are header keywords that are commonly updated
    # Dictionary values are standard comments for each keyword
    "AMPNAME": "Amplifier name(s)",
    "BIASIM": "Bias image used",
    "BPMNAME": "Name of BPM used to identify bad pixels",
    "BUNIT": "Physical units of the array values",
    "CCDSEC": "CCD section(s)",
    "CD1_1": "WCS matrix element 1 1",
    "CD1_2": "WCS matrix element 1 2",
    "CD2_1": "WCS matrix element 2 1",
    "CD2_2": "WCS matrix element 2 2",
    "CRPIX1": "Ref pix of axis 1",
    "CRPIX2": "Ref pix of axis 2",
    "CRVAL1": "RA at Ref pix in decimal degrees",
    "CRVAL2": "DEC at Ref pix in decimal degrees",
    "DARKIM": "Dark image used",
    "DATALAB": "DHS data label",
    "DATASEC": "Data section(s)",
    "DEC": "Declination of Target",
    "DETSEC": "Detector section(s)",
    "DISPAXIS": "Dispersion axis",
    "EXPTIME": "Exposure time [seconds]",
    "FILTER": "Combined filter name",
    "FLATIM": "Flat image used",
    "FRINGEIM": "Fringe image used",
    "GAIN": "Gain [electrons/ADU]",
    "GAINSET": "Gain setting (low / high)",
    "GEMPRGID": "Gemini program ID",
    "MEANFWHM": "Mean point source FWHM (arcsec)",
    "MEANELLP": "Mean point source ellipticity",
    "NAXIS1": "Axis length",
    "NAXIS2": "Axis length",
    "NEXTEND": "Number of extensions",
    "NONLINEA": "Non-linear regime [ADU]",
    "NSCIEXT": "Number of science extensions",
    "OBJECT": "Object Name",
    "OBSCLASS": "Observe class",
    "OBSID": "Observation ID / Data label",
    "OBSTYPE": "Observation type",
    "ORIGNAME": "Original filename prior to processing",
    "OVERSCAN": "Overscan mean value",
    "PIXSCALE": "Pixel scale [arcsec/pixel]",
    "RA": "Right Ascension",
    "RAWGEMQA": "Gemini Quality Assessment",
    "RAWPIREQ": "PI Requirements Met",
    "RDNOISE": "Estimated read noise [electrons]",
    "RELEASE": "End of proprietary period YYYY-MM-DD",
    "RELINT": "Relative intensity factor",
    "SATLEVEL": "Saturation level [ADU]",
    "SKYLEVEL": "Estimated sky level",
    "TRIMMED": "Overscan section trimmed",
    "TRIMSEC": "Data section prior to trimming",
}
