timestamp_keys = {
    # Dictionary key is the name of the user level function (in alphabetical
    # order)
    # Dictionary value is the timestamp keyword that should be used when
    # writing a timestamp keyword to the header once the user level function
    # has completed
    "addDQ": "ADDDQ",
    "add_mdf": "ADDMDF",
    "add_objcat": "ADDOBCAT",
    "addReferenceCatalog": "ADDRECAT",
    "addVAR": "ADDVAR",
    "aduToElectrons": "ADUTOELE",
    "alignToReferenceImage": "ALIGN",
    "correct_background_to_reference_image": "CORRBG",
    "correctWCSToReferenceImage": "CORWCSIM",
    "cut_slits": "CUTSLITS",
    "detect_sources": "DETECSRC",
    "determineAstrometricSolution": "ASTRMTRY",
    "divideByFlat": "DIVFLAT",
    "makeFlat": "MAKEFLAT",
    "makeFringeFrame": "FRINGE",
    "match_objcat_refcat" : "MATORCAT",
    "measure_bg": "MEASREBG",
    "measure_iq": "MEASREIQ",
    "measureZP": "MEASREZP",
    "mosaic_detectors": "MOSAIC",
    "nonlinearityCorrect": "LINCORR",
    "normalize": "NORMLIZE",
    "normalize_image_gmos": "NORMLIZE",
    "prepare": "PREPARE",
    "remove_fringe_image_gmos": "RMFRINGE",
    "separate_sky": "SEPSKY",
    "scale_by_intensity": "SCALEINT",
    "stackFrames": "STACKFRM",
    "standardize_headers_f2": "SDZHDRSI",
    "standardize_headers_gemini": "SDZHDRSG",
    "standardize_headers_gmos": "SDZHDRSI",
    "standardize_structure_f2": "SDZSTRUC",
    "standardize_structure_gmos": "SDZSTRUC",
    "subtractBias": "SUBBIAS",
    "subtractDark": "SUBDARK",
    "subtractOverscan": "SUBOVER",
    "subtract_sky": "SUBSKY",
    "tile_arrays": "TILEARRY",
    "trim_overscan": "TRIMOVER",
    "trace_slits": "TRACESLI",
    "validateData": "VALDATA",
    }
