timestamp_keys = {
    # Dictionary key is the name of the user level function (in alphabetical
    # order)
    # Dictionary value is the timestamp keyword that should be used when
    # writing a timestamp keyword to the header once the user level function
    # has completed
    "addDQ": "ADDDQ",
    "addMDF": "ADDMDF",
    "addReferenceCatalog": "ADDRECAT",
    "addVAR": "ADDVAR",
    "aduToElectrons": "ADUTOELE",
    "alignToReferenceImage": "ALIGN",
    "applyObjectMask": "APOBJMSK",
    "correctBackgroundToReferenceImage": "CORRBG",
    "correctWCSToReferenceImage": "CORWCSIM",
    "cut_slits": "CUTSLITS",
    "detectSources": "DETECSRC",
    "determineAstrometricSolution": "ASTRMTRY",
    "divideByFlat": "DIVFLAT",
    "makeFlat": "MAKEFLAT",
    "makeFringeFrame": "FRINGE",
    "measureBG": "MEASREBG",
    "measureIQ": "MEASREIQ",
    "measureZP": "MEASREZP",
    "mosaicDetectors": "MOSAIC",
    "nonlinearityCorrect": "LINCORR",
    "normalize": "NORMLIZE",
    "prepare": "PREPARE",
    "removeFringe": "RMFRINGE",
    "scaleByIntensity": "SCALEINT",
    "separateSky": "SEPSKY",
    "stackFrames": "STACKFRM",
    "standardizeCommonHeaders": "SDZHDRSC",
    "standardizeInstrumentHeaders": "SDZHDRSI",
    "standardizeStructure": "SDZSTRUC",
    "subtractBias": "SUBBIAS",
    "subtractDark": "SUBDARK",
    "subtractOverscan": "SUBOVER",
    "subtractSky": "SUBSKY",
    "tileArrays": "TILEARRY",
    "trimOverscan": "TRIMOVER",
    "trace_slits": "TRACESLI",
    "validateData": "VALDATA",
    }
