F2_KeyDict = {
    "key_camera":"LYOT",
    "key_cd11":"CD1_1",
    "key_cd12":"CD1_2",
    "key_cd21":"CD2_1",
    "key_cd22":"CD2_2",
    "key_central_wavelength":"GRWLEN",
    "key_disperser":"GRISM",
    "key_filter1":"FILTER1",
    "key_filter2":"FILTER2",
    "key_focal_plane_mask":"MOSPOS",
    "key_lnrs":"LNRS",
    "key_lyot_stop":"LYOT",
    "key_old_filter1":"FILT1POS",
    "key_old_filter2":"FILT2POS",
    "key_old_grating":"GRISMPOS",
    }
