timestamp_keys = {
    # Dictionary key is the name of the user level function (in alphabetical
    # order)
    # Dictionary value is the timestamp keyword that should be used when
    # writing a timestamp keyword to the header once the user level function
    # has completed
    "add": "ADD",
    "addDQ": "ADDDQ",
    "addIllumMaskToDQ": "ADILLMSK",
    "addMDF": "ADDMDF",
    "addObjectMaskToDQ": "ADOBJMSK",
    "addReferenceCatalog": "ADDRECAT",
    "addVAR": "ADDVAR",
    "ADUToElectrons": "ADUTOELE",
    "alignToReferenceFrame": "ALIGN",
    "applyDQPlane": "APLDQPLN",
    "associateSky": "ASSOCSKY",
    "attachWavelengthSolution": "ATTWVSOL",
    "correctBackgroundToReferenceImage": "CORRBG",
    "correctWCSToReferenceFrame": "CORRWCS",
    "cutFootprints": "CUTSFP",
    "detectSources": "DETECSRC",
    "appwave": "APPWAVE",
    "determineWaveCalSolution": "WAVECAL",
    "determineWavelengthSolution": "WAVESOLN",
    "determineAstrometricSolution": "ASTRMTRY",
    "divide": "DIVIDE",
    "divideByFlat": "DIVFLAT",
    "extract1DSpectra": "EXTRACT",
    "makeFlat": "MAKEFLAT",
    "makeFringeFrame": "FRINGE",
    "measureBG": "MEASREBG",
    "measureIQ": "MEASREIQ",
    "measureCC": "MEASRECC",
    "mosaicDetectors": "MOSAIC",
    "mosaicADdetectors": "MOSAIC",
    "multiply": "MULTIPLY",
    "nonlinearityCorrect": "LINCORR",
    "normalizeFlat": "NORMLIZE",
    "prepare": "PREPARE",
    "rejectCosmicRays": "REJECTCR",
    "resampleToLinearCoords": "LINCOORD",
    "wcalResampleToLinearCoords": "LINCOORD",
#    "scaleByExposureTime": "EXPSCALE",
    "scaleByIntensity": "SCALEINT",
    "scaleFringeToScience": "SCLFRING",
    "separateSky": "SEPSKY",
    "skyCorrectFromSlit": "SKYCORR",
    "stackFrames": "STACKFRM",
    "stackSkyFrames": "STACKSKY",
    "standardizeGeminiHeaders": "SDZHDRSG",
    "standardizeInstrumentHeaders": "SDZHDRSI",
    "standardizeStructure": "SDZSTRUC",
    "subtract": "SUBTRACT",
    "subtractBias": "SUBBIAS",
    "subtractDark": "SUBDARK",
    "subtractFringe": "SUBFRING",
    "subtractOverscan": "SUBOVER",
    "subtractSky": "SUBSKY",
    "subtractSkyBackground": "SUBSKYBG",
    "thresholdFlatfield": "TRHFLAT",
    "tileArrays": "TILEARRY",
    "trimOverscan": "TRIMOVER",
    "traceFootprints": "TRACEFP",
    "updateWCS": "UPDATWCS",
    "validateData": "VALDATA",
    }
