NIRI_KeyDict = {
    "key_avdduc":"A_VDDUC",
    "key_avdet":"A_VDET",
    "key_cd11":"CD1_1",
    "key_cd12":"CD1_2",
    "key_cd21":"CD2_1",
    "key_cd22":"CD2_2",
    "key_filter1":"FILTER1",
    "key_filter2":"FILTER2",
    "key_filter3":"FILTER3",
    "key_hicol":"HICOL",
    "key_hirow":"HIROW",
    "key_lnrs":"LNRS",
    "key_lowcol":"LOWCOL",
    "key_lowrow":"LOWROW",
    "key_ndavgs":"NDAVGS",
    }
