stdkeyDictGNIRS = {
    "key_gnirs_bias":"DETBIAS",
    "key_gnirs_camera":"CAMERA",
    "key_gnirs_coadds":"COADDS",
    "key_gnirs_cwave":"GRATWAVE",
    "key_gnirs_decker":"DECKER",
    "key_gnirs_disperser":"GRATING",
    "key_gnirs_exptime":"EXPTIME",
    "key_gnirs_filter1":"FILTER1",
    "key_gnirs_filter2":"FILTER2",
    "key_gnirs_fpmask":"SLIT",
    "key_gnirs_lnrs":"LNRS",
    "key_gnirs_ndavgs":"NDAVGS",
    "key_gnirs_prism":"PRISM",
    }
