#!/usr/bin/env python
# -*- coding: utf8 -*-
import sys
from gempy.utils import showrecipes


__author__ = 'Ivan Sharankov'


def main():
    args = showrecipies_argparser()
    recipes_found = showrecipes.showrecipes(args.inputfile)
    print(recipes_found)

def showrecipies_argparser():

    from argparse import ArgumentParser
    from argparse import RawDescriptionHelpFormatter

    parser = ArgumentParser(description="desc", prog='showrecipes',
                            formatter_class=RawDescriptionHelpFormatter)

    parser.add_argument('inputfile', type=str,
                        help="The fits file needed to extract the tags. This "
                            "file must be opened by astrodata as an object")


    return parser.parse_args()


if __name__ == "__main__":
    main()


