#!/usr/bin/env python
# -*- coding: utf8 -*-

from __future__ import print_function

from argparse import ArgumentParser, RawDescriptionHelpFormatter

from gempy.utils import showrecipes

__author__ = 'Ivan Sharankov'


def main():
    parser = ArgumentParser(
        description="Shows what sequence of primitives a recipe will execute "
        "or which recipes are available for the dataset.",
        formatter_class=RawDescriptionHelpFormatter
    )
    parser.add_argument('inputfile', type=str,
                        help="The fits file needed to extract the tags. This "
                             "file must be opened by astrodata as an object")

    parser.add_argument("-m", "--mode", dest="mode", default='sq',
                        help="determines if the mode of the recipe "
                             "is either 'qa' or 'sq'.")

    parser.add_argument("-r", "--recipe", dest="recipe", default='_default',
                        help="Determines the recipe that the user wants "
                             "to see the primitives for. If no recipe is "
                             " provided, the default is used.")

    parser.add_argument("--all", default=False, action='store_true',
                        help='Show the name of all the valid recipes.')

    parser.add_argument("--debug", default=False, action='store_true',
                        help='Print debugging statements')

    args = parser.parse_args()

    if args.debug:
        print(args)

    if args.all:
        recipes_found = showrecipes.showrecipes(args.inputfile)
        print(recipes_found)
    else:
        primitives_found = showrecipes.showprims(
            args.inputfile, args.mode, args.recipe)
        print(primitives_found)


if __name__ == "__main__":
    main()
