#!/usr/bin/env python

"""
App to print to screen descriptor values for astrodata-supported FITS files.

Eg. showd N20120212S0012.fits -d camera filter_name
    showd N20120212S*.fits -d camera filter_name
"""

from __future__ import print_function

import sys
import argparse

import astrodata
import gemini_instruments

SHORT_DESCRIPTION = "For each input file, show the value of the specified descriptors."

def get_descriptor_value(ad, descriptors):
    """
    Return the descriptor values as a list of DescriptorValue objects.

    Parameters
    ----------
    ad : AstroData object
        The AstroData object we are probing.
    descriptors : list of str
        A list of strings each equivalent to the name of the descriptor
        one wants to access.

    Returns
    -------
    A list of DescriptorValue objects.

    Raises
    ------
    See Also
    --------
    Examples
    --------
    ad = AstroData('filename.fits')
    descriptors = ['camera', 'filter_name']
    values = get_descriptor_value(ad, descriptors)
    """
    values = []
    for descriptor in descriptors:
        values.append(getattr(ad, descriptor)())
    return values


def parse_args(command_line_args):
    """
    Parse the command line.
    """
    parser = argparse.ArgumentParser(description=SHORT_DESCRIPTION)
    parser.add_argument('inputs', type=str, nargs="*",
                        help="Input FITS files")
    parser.add_argument('--descriptors', '-d', type=str, nargs=1,
                        dest='descriptors', action='store', required=True,
                        help='comma-separated list of descriptor values to return')
    parser.add_argument('--debug', default=False, action='store_true',
                        help='Toggle debug mode')

    args = parser.parse_args(command_line_args)

    args.descriptors = args.descriptors[0].split(',')

    if args.debug:
        print(args)

    return args


def main(argv=None):
    """
    Print the requested descriptor values for each input files.
    One file per line.
    """
    if argv is None:
        argv = sys.argv[1:]

    if not sys.stdin.isatty():
        input_stream = [fname.rstrip() for fname in sys.stdin]
        argv[0:0] = input_stream

    args = parse_args(argv)

    hdr = "\nfilename:"
    for descriptor in args.descriptors:
        hdr += '   '+descriptor
    hdr += '\n------------------------------'
    print(hdr)
    for filename in args.inputs:
        ad = astrodata.open(filename)
        values = get_descriptor_value(ad, args.descriptors)
        msg = "%s: " % ad.filename
        for value in values:
            msg += "%s " % value
        print(msg)


if __name__ == '__main__':
    sys.exit(main())