#!/usr/bin/env python
# -*- coding: utf8 -*-
import sys
from gempy.utils import show_primitives


__author__ = 'Ivan Sharankov'

def main():
    args = show_primitives_argparser()
    show_primitives.show_primitives(args.inputfile, args.mode, args.recipe)



def show_primitives_argparser():
    from argparse import ArgumentParser
    from argparse import RawDescriptionHelpFormatter

    parser = ArgumentParser(description="desc", prog='show_primitives',
                            formatter_class=RawDescriptionHelpFormatter)

    parser.add_argument('inputfile', type=str,
                    help="The fits file needed to extract the tags. This "
                            "file must be opened by astrodata as an object")

    parser.add_argument("-m", "--mode", dest="mode", default='sq',
                        help="determines if the mode of the recipe "
                             "is either 'qa' or 'sq'.")


    parser.add_argument("-r", "--recipe", dest="recipe", default='default',
                        help="Determines the recipe that the user wants "
                             "to see the primitives for. If no recipe is "
                             " provided, the default is used.")

    return parser.parse_args()


if __name__ == "__main__":
    main()