name: Run development tests

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 53 3 * * 0

jobs:
  tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        shell: bash -l {0}
        run: python -m pip install nox

      - name: Run dev tests
        shell: bash -l {0}
        run: |
          nox -s run_dev_tests -- -vv
