name: Run development tests

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 53 3 * * 0

jobs:
  dev_tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          conda-remove-defaults: true
          miniforge-version: latest

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.11
            3.12
            3.13


      - name: Run dev tests
        run: |
          nox -s run_dev_tests -- -vv
