name: Run development tests

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 53 3 * * 0

jobs:
  tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          conda-remove-defaults: true

      - uses: actions/checkout@v2
      - uses: excitedleigh/setup-nox@v2.0.0
      - run: nox -s run_dev_tests -- -vv
