# Linting and format-checking workflow for the repository.
#
# Behavior in this file, other than setup, is controlled in the file
# .pre-commit-config.yaml in the top directory of the repository.
#
# Any automations should be added to that file. This check runs over the entire
# repository, not just changes.
name: Lint repository

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    # Run every Sunday at 03:53 UTC
    - cron: 53 3 * * 0

jobs:
  tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.12"]
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5


      - name: Install packages
        shell: bash -l {0}
        run: python -m pip install nox

      - name: Run dev tests
        shell: bash -l {0}
        run: |
          nox -s lint
